name: flutter_countries_states
description: A Flutter application that displays countries and states using clean architecture.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

  # Architecture
  equatable: ^2.0.5
  dartz: ^0.10.1
  get_it: ^7.6.0

  # State Management
  flutter_bloc: ^8.1.3

  # Network
  http: ^1.1.0
  internet_connection_checker: ^1.0.0+1

  # Code Generation
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  bloc_test: ^9.1.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

  # Testing
  mockito: ^5.4.2
  build_runner: ^2.4.6
  freezed: ^2.4.5
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
