// Mocks generated by Mockito 5.4.4 from annotations
// in flutter_countries_states/test/repo/backup_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:flutter_countries_states/data/model/location_model.dart' as _i4;
import 'package:flutter_countries_states/data/repo/location_backupsource.dart'
    as _i2;
import 'package:flutter_countries_states/device/network_info.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [LocationBackupDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockLocationBackupDataSource extends _i1.Mock
    implements _i2.LocationBackupDataSource {
  MockLocationBackupDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.LocationModel>> getCountries() => (super.noSuchMethod(
        Invocation.method(
          #getCountries,
          [],
        ),
        returnValue:
            _i3.Future<List<_i4.LocationModel>>.value(<_i4.LocationModel>[]),
      ) as _i3.Future<List<_i4.LocationModel>>);

  @override
  _i3.Future<List<_i4.LocationModel>> getStates(String? countryName) =>
      (super.noSuchMethod(
        Invocation.method(
          #getStates,
          [countryName],
        ),
        returnValue:
            _i3.Future<List<_i4.LocationModel>>.value(<_i4.LocationModel>[]),
      ) as _i3.Future<List<_i4.LocationModel>>);

  @override
  _i3.Future<String?> getCountryCodeByName(String? countryName) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCountryCodeByName,
          [countryName],
        ),
        returnValue: _i3.Future<String?>.value(),
      ) as _i3.Future<String?>);
}

/// A class which mocks [NetworkInfo].
///
/// See the documentation for Mockito's code generation for more information.
class MockNetworkInfo extends _i1.Mock implements _i5.NetworkInfo {
  MockNetworkInfo() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<bool> get isConnected => (super.noSuchMethod(
        Invocation.getter(#isConnected),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);
}
